import React from 'react'
import Head from "next/head";
import Image from "next/image";
import Link from 'next/link'
import styles from "@/styles/Home.module.css";
import { Footer } from "./index";

const Items = () => {
  return (
    <div>
    <Head>
    <title>Crypt captivating</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    <script src="https://cdn.tailwindcss.com"></script>
</Head>
    <section className="navbar-theme">
    <div className="container flex flex-wrap p-5 pl-10 bg-dark flex-col text-white md:flex-row items-center">
      <a className="flex title-font font-medium items-center text-white mb-4 md:mb-0">
        {/* Logo */}
        <Image src="/Crypt-logo.png" alt="Crypt logo" height="80" width="80" />
        <span className="ml-3 -mr-14 text-white text-xl">Crypt Captivating</span>
      </a>
      <nav className="ml-96 mr-20 md:mr-auto flex flex-wrap items-center text-base justify-center">
        <Link href="/" className="mr-5 hover:text-gray-400">Home
        </Link>
        <Link href="/components/about" className="mr-5 hover:text-gray-400">
          About
        </Link>
        <Link href="/components/items" className="mr-5 hover:text-gray-400">
          Items
        </Link>
        <Link href="/components/contact" className="mr-5 hover:text-gray-400">Contact
        </Link>
        <Link href="/components/wallet" className="mr-5 hover:text-gray-400">Wallet
        </Link>
      </nav>
      <Link href="/components/wallet">
      <button className="inline-flex items-center bg-gradient-to-r from-lime-500 to-green-600 border-0 py-2 px-6 focus:outline-none hover:bg-gradient-to-l from-green-500 to-lime-600 text-white border-0 -mr-10 py-2 px-5 rounded text-base mt-4 md:mt-0">Check Balance
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </button>
      </Link>
      
    </div>
    </section>

    <section className="text-gray-600 body-font overflow-hidden">
  <div className="container px-5 py-24 mx-auto">
    <div className="lg:w-4/5 mx-auto flex flex-wrap">
      <div className="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 className="text-sm title-font text-gray-500 tracking-widest">BRAND NAME</h2>
        <h1 className="text-gray-900 text-3xl title-font font-medium mb-4">Kick Start Farming</h1>
        <div className="flex mb-4">
          <a className="flex-grow text-green-500 border-b-2 border-green-500 py-2 text-lg px-1">Description</a>
          <a className="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a className="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
        </div>
        <p className="leading-relaxed mb-4">Farming is the practice of cultivating crops and raising animals for food, fiber, and other products. It has been a crucial part of human civilization for thousands of years, allowing people to settle in one place and form communities. Today, modern farming methods involve the use of machinery, fertilizers, and pesticides to increase efficiency and yield. However, there are growing concerns about the environmental impact of industrial agriculture and the need for sustainable, regenerative farming practices..</p>
        <div className="flex border-t border-gray-200 py-2">
          <span className="text-gray-500">Category</span>
          <span className="ml-auto text-gray-900">Vegetables</span>
        </div>
        <div className="flex border-t border-gray-200 py-2">
          <span className="text-gray-500">Price</span>
          <span className="ml-auto text-gray-900">Every vegetables at 0.05 Eth</span>
        </div>
        <div className="flex border-t border-b mb-6 border-gray-200 py-2">
          <span className="text-gray-500">Quantity</span>
          <span className="ml-auto text-gray-900">17500 Pieces in all Category</span>
        </div>
        <span className="title-font font-medium text-2xl text-gray-900">My net worth</span><br />
        <div className="flex"> 
          <span className="title-font font-medium text-2xl text-gray-900">Ξ 58.00</span>
          <button className="flex ml-auto text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded">Buy things from me</button>
          <button className="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <Image src="/items-farmer.jpg" alt="Farmer images" height="400" width="480"/>
    </div>
  </div>
</section>
<section className="">
<h2 className="text-center text-5xl font-bold pt-10">Here are the things that we have</h2>
<p className='text-center mt-5 text-xl'>"Eat your veggies, they'll keep you fit, strong and hearty,
A simple, healthy choice that's always a smart party."</p>
<div className="container px-5 py-24 mx-auto">
  <div className="flex flex-wrap -m-4">
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/tomato.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
      </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Tomato</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/onion.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
     </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Onion</h2>
        <p className="mt-1">Ξ 0.006 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/potatoes.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
        </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Potato</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/brinjal.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Brinjal</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/ladyFinger.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />

         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Lady finger</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/greenChillies.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
       </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Green chillies</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/pumkin.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />

         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Pumkin</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/brocoli.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
        </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Brocoli</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
  </div>
</div>
    </section>
    <hr className="ml-28 mr-28" />
<section className="">
<h2 className="text-center text-2xl font-bold pt-10">Have a look at what we have</h2>
<p className='text-center mt-5 text-xl'>"Eat your veggies, they'll keep you fit, strong and hearty,
A simple, healthy choice that's always a smart party."</p>
<div className="container px-5 py-24 mx-auto">
  <div className="flex flex-wrap -m-4">
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/tomato.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
      </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Tomato</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/onion.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
     </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Onion</h2>
        <p className="mt-1">Ξ 0.006 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/potatoes.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
        </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Potato</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/brinjal.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Brinjal</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/ladyFinger.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />

         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Lady finger</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/greenChillies.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
       </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Green chillies</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/pumkin.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />

         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Pumkin</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/brocoli.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
        </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Brocoli</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
  </div>
</div>

<hr className="ml-28 mr-28" />

<h2 className="text-center text-2xl font-bold pt-10">Have a look at what we have</h2>
<p className='text-center mt-5 text-xl'>"Eat your veggies, they'll keep you fit, strong and hearty,
A simple, healthy choice that's always a smart party."</p>
<div className="container px-5 py-24 mx-auto">
  <div className="flex flex-wrap -m-4">
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/tomato.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
      </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Tomato</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/onion.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
     </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Onion</h2>
        <p className="mt-1">Ξ 0.006 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/potatoes.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
        </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Potato</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/brinjal.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Brinjal</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/ladyFinger.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />

         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Lady finger</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/greenChillies.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
       </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Green chillies</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/pumkin.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />

         </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Pumkin</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a className="block relative h-48 rounded overflow-hidden">
        <Image src="/brocoli.jpg" alt="Vegetables" width="600" height="500" className='rounded-2xl' />
        </a>
      <div className="mt-4">
        <h3 className="text-white-500 text-xs tracking-widest title-font mb-1">CATEGORY VEGETABLES</h3>
        <h2 className="text-white-900 title-font text-lg font-medium">Brocoli</h2>
        <p className="mt-1">Ξ 0.005 ETH</p>
      </div>
    </div>
  </div>
</div>

<hr className="ml-28 mr-28" />
    
  {/*/ <span className='ml-52'/><button className="inline-flex items-center bg-gradient-to-r from-lime-500 to-green-600 border-0 py-2 px-6 focus:outline-none hover:bg-gradient-to-l from-green-500 to-lime-600 text-white border-0 py-2 px-5 rounded text-base -mt-10 mb-10 ml-96 md:mt-0">Search More
<svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-4 h-4 ml-1" viewBox="0 0 24 24">
  <path d="M5 12h14M12 5l7 7-7 7"></path>
</svg>
</button> /*/}

</section>
    <div className="flex font-sans">
  <div className="flex-none w-48 relative">
    <img src="/classNameic-utility-jacket.jpg" alt="" className="absolute inset-0 w-full h-full object-cover" loading="lazy" />
  </div>
  <form className="flex-auto p-6">
    <div className="flex flex-wrap">
      <h1 className="flex-auto text-lg font-semibold text-slate-900">
        classNameic Utility Jacket
      </h1>
      <div className="text-lg font-semibold text-slate-500">
        $110.00
      </div>
      <div className="w-full flex-none text-sm font-medium text-slate-700 mt-2">
        In stock
      </div>
    </div>
    <div className="flex items-baseline mt-4 mb-6 pb-6 border-b border-slate-200">
      <div className="space-x-2 flex text-sm">
        <label>
          <input className="sr-only peer" name="size" type="radio" value="xs" checked />
          <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
            XS
          </div>
        </label>
        <label>
          <input className="sr-only peer" name="size" type="radio" value="s" />
          <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
            S
          </div>
        </label>
        <label>
          <input className="sr-only peer" name="size" type="radio" value="m" />
          <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
            M
          </div>
        </label>
        <label>
          <input className="sr-only peer" name="size" type="radio" value="l" />
          <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
            L
          </div>
        </label>
        <label>
          <input className="sr-only peer" name="size" type="radio" value="xl" />
          <div className="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
            XL
          </div>
        </label>
      </div>
    </div>
    <div className="flex space-x-4 mb-6 text-sm font-medium">
      <div className="flex-auto flex space-x-4">
        <button className="h-10 px-6 font-semibold rounded-md bg-black text-white" type="submit">
          Buy now
        </button>
        <button className="h-10 px-6 font-semibold rounded-md border border-slate-200 text-slate-900" type="button">
          Add to bag
        </button>
      </div>
      <button className="flex-none flex items-center justify-center w-9 h-9 rounded-md text-slate-300 border border-slate-200" type="button" aria-label="Like">
        <svg width="20" height="20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" />
        </svg>
      </button>
    </div>
    <p className="text-sm text-slate-700">
      Free shipping on all continental US orders.
    </p>
  </form>
</div>
<section>
<Footer />
</section>
</div>

  )
}

export default Items